### ISSUE TITLE
Apache POI is a trademark owned by the Apache Software Foundation

### ISSUE THREAD

**Issue by pjfanning** [T5750/poi-repositories#8]
It is generally accepted that you can't infringe on trademarks owned by other legal entities. Could you rename this project?

Apache is also a registered trademark owned by the Apache Software Foundation. I think you need to update this repo and the docs in https://poix.readthedocs.io/en/latest/ to highlight that you have no affiliation whatsoever to Apache POI or the Apache Software Foundation.

I have brought this to the attention of the Apache Software Foundation team in charge of the Apache Software Foundation trademarks.

**Comment by T5750** [comment]
> It is generally accepted that you can't infringe on trademarks owned by other legal entities. Could you rename this project?
> 
> Apache is also a registered trademark owned by the Apache Software Foundation. I think you need to update this repo and the docs in https://poix.readthedocs.io/en/latest/ to highlight that you have no affiliation whatsoever to Apache POI or the Apache Software Foundation.
> 
> I have brought this to the attention of the Apache Software Foundation team in charge of the Apache Software Foundation trademarks.

OK, I have no intention of infringing trademarks owned by other legal entities.

This project aims to learn and integrate Apache POI.

**Comment by pjfanning** [comment]
Thanks @T5750 for renaming the repo. I'll close this issue because this reduces any potential for confusion.
